### PR TITLE
Makefile tweaks

### PR DESCRIPTION
**Pull request by anntnzrb**
Info @ commit.

### CODE REVIEW

**Review by Nyx-alpha — CHANGES_REQUESTED** [review]
Add BSD LDFLAGS for compling
`# FreeBSD (uncomment)`
`#LDFLAGS += -L/usr/local/lib -I/usr/local/include`
`# OpenBSD (uncomment)`
`#LDFLAGS += -L/usr/X11R6/lib -I/usr/X11R6/include`

hardcode `${RM}` to `rm -f`

**Comment by anntnzrb** [comment]
> hardcode `${RM}` to `rm -f`

Why is this? portability related? both should be equivalent.

**Comment by Nyx-alpha** [comment]
> > hardcode `${RM}` to `rm -f`
> 
> Why is this? portability related? Shouldn't both be equivalent?

Yep, it's a portability thing. They are the equivalent but not all Make versions, such as the make FreeBSD uses, have the RM variable built-in.
Technically you could define it at the top with `RM= rm -f`. Personally would recommend hard-coding it since there are only 2 lines and it could avoid issues overwriting the built-in variable; not that I would expect there to be any.

**Comment by anntnzrb** [comment]
> They are the equivalent but not all Make versions, such as the make FreeBSD uses, have the RM variable built-in.

Great to know, I've committed the corresponding changes.

**Pull request merged**
